import React from "react";
import { Award, Percent } from "lucide-react";
import { BarChart, Bar, ResponsiveContainer, XAxis, YAxis, Tooltip, CartesianGrid } from "recharts";
export default function LiveMembershipReport({ data }) {
  return <section className="space-y-4"><h2 className="text-xs font-semibold uppercase tracking-wider text-black/40">Membership</h2>
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-4"><div className="bg-white border border-black/10 rounded-xl p-5 flex items-center gap-4"><div className="w-12 h-12 rounded-lg bg-black text-white flex items-center justify-center"><Award className="w-6 h-6" /></div><div><p className="text-xs text-black/40">Most Popular Plan</p><p className="text-lg font-bold">{data.mostPopularPlan}</p></div></div><div className="bg-white border border-black/10 rounded-xl p-5 flex items-center gap-4"><div className="w-12 h-12 rounded-lg bg-black text-white flex items-center justify-center"><Percent className="w-6 h-6" /></div><div><p className="text-xs text-black/40">Renewal Rate</p><p className="text-lg font-bold">{data.renewalRate == null ? "N/A" : `${data.renewalRate}%`}</p></div></div>
      <div className="bg-white border border-black/10 rounded-xl p-5"><h3 className="font-semibold text-sm mb-2">Active Subscriptions</h3>{data.planPerformance.length === 0 ? <p className="text-xs text-black/45">No subscriptions yet</p> : data.planPerformance.map((p) => <div key={p.plan} className="flex justify-between text-xs py-1"><span>{p.plan}</span><b>{p.count}</b></div>)}</div></div>
    <div className="bg-white border border-black/10 rounded-xl p-4 md:p-5"><h3 className="font-semibold">Expiration Trends</h3><p className="text-xs text-black/50 mb-4">Expired memberships from real records</p><div className="h-56"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.series}><CartesianGrid strokeDasharray="3 3" stroke="#00000010" vertical={false} /><XAxis dataKey="label" tick={{ fontSize: 12 }} axisLine={false} tickLine={false} /><YAxis allowDecimals={false} tick={{ fontSize: 12 }} axisLine={false} tickLine={false} /><Tooltip /><Bar dataKey="expired" fill="#000" radius={[6, 6, 0, 0]} /></BarChart></ResponsiveContainer></div></div>
  </section>;
}