import React, { useState } from "react";
import { Plus, MessageSquare } from "lucide-react";
import MemberLayout from "@/components/MemberLayout";
import MemberDataState from "@/components/member/MemberDataState";
import Modal from "@/components/ui/Modal";
import { useToast } from "@/components/ui/use-toast";
import { useMemberPortal, createMemberFeedback } from "@/lib/memberPortalStore";
const types = ["Feedback", "Complaint", "Feature Request", "Machine Request", "Coach Request"];
const statuses = ["All", "Pending", "Under Review", "Approved", "Rejected", "Completed"];
const input = "w-full px-3 py-2.5 rounded-lg border border-black/15 bg-white text-sm outline-none focus:border-black";
export default function MemberFeedback() {
  const { data, loaded, error } = useMemberPortal();
  const [open, setOpen] = useState(false); const [filter, setFilter] = useState("All"); const [saving, setSaving] = useState(false);
  const [form, setForm] = useState({ type: "Feedback", title: "", body: "" }); const { toast } = useToast();
  if (!loaded) return <MemberLayout title="Feedback"><div className="h-80 bg-black/5 animate-pulse rounded-xl" /></MemberLayout>;
  if (!data) return <MemberDataState title="Feedback" error={error} />;
  const requests = filter === "All" ? data.feedback : data.feedback.filter((item) => item.status === filter);
  const submit = async () => { if (!form.title.trim() || !form.body.trim()) return; setSaving(true); try { await createMemberFeedback(form); setOpen(false); setForm({ type: "Feedback", title: "", body: "" }); toast({ title: "Request submitted", description: "Your gym will review it shortly." }); } catch (err) { toast({ title: "Request failed", description: err.message }); } finally { setSaving(false); } };
  return <MemberLayout title="Feedback" back="/member"><div className="space-y-5"><div className="flex items-center justify-between"><div><h1 className="text-xl font-bold">Feedback & Requests</h1><p className="text-sm text-black/50">Send a request to your gym</p></div><button onClick={() => setOpen(true)} className="flex gap-1.5 px-3 py-2 bg-black text-white rounded-lg text-sm"><Plus className="w-4 h-4" /> New</button></div><div className="flex gap-1.5 overflow-x-auto">{statuses.map((status) => <button key={status} onClick={() => setFilter(status)} className={`px-3 py-1.5 rounded-lg text-xs border whitespace-nowrap ${filter === status ? 'bg-black text-white' : 'bg-white'}`}>{status}</button>)}</div>{requests.length === 0 ? <div className="text-center py-10 border border-dashed rounded-xl"><MessageSquare className="w-7 h-7 mx-auto text-black/30" /><p className="text-sm font-medium mt-2">No requests here</p></div> : <div className="space-y-3">{requests.map((item) => <div key={item.id} className="border border-black/10 rounded-xl p-4"><div className="flex justify-between"><span className="text-xs text-black/50">{item.type}</span><span className="text-xs font-semibold">{item.status}</span></div><h3 className="text-sm font-semibold mt-2">{item.title}</h3><p className="text-sm text-black/50 mt-1">{item.body}</p><p className="text-xs text-black/40 mt-3">{item.date}</p>{item.response && <p className="text-sm mt-3 border-t pt-3"><b>Gym:</b> {item.response}</p>}</div>)}</div>}<Modal open={open} onClose={() => setOpen(false)} title="New request" footer={<><button onClick={() => setOpen(false)} className="px-4 py-2 text-sm border rounded-lg">Cancel</button><button onClick={submit} disabled={saving} className="px-4 py-2 text-sm bg-black text-white rounded-lg disabled:opacity-50">{saving ? 'Submitting…' : 'Submit'}</button></>}><div className="space-y-4"><label className="block text-sm font-medium">Request type<select className={`${input} mt-1.5`} value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value })}>{types.map((type) => <option key={type}>{type}</option>)}</select></label><label className="block text-sm font-medium">Title<input className={`${input} mt-1.5`} value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></label><label className="block text-sm font-medium">Details<textarea rows={4} className={`${input} mt-1.5`} value={form.body} onChange={(e) => setForm({ ...form, body: e.target.value })} /></label></div></Modal></div></MemberLayout>;
}