import React from "react";
import { Phone, Mail, Calendar, Dumbbell } from "lucide-react";
import MemberLayout from "@/components/MemberLayout";
import MemberDataState from "@/components/member/MemberDataState";
import { useMemberPortal } from "@/lib/memberPortalStore";
import { membershipProgress } from "@/lib/memberPortalUtils";
const Row = ({ icon: Icon, label, value }) => <div className="flex items-center gap-3 py-3 border-b border-black/5"><div className="w-9 h-9 rounded-lg bg-black/5 flex items-center justify-center"><Icon className="w-4 h-4" /></div><div><p className="text-xs text-black/50">{label}</p><p className="text-sm font-semibold">{value || '—'}</p></div></div>;
export default function MemberProfile() {
  const { data, loaded, error } = useMemberPortal();
  if (!loaded) return <MemberLayout title="Profile"><div className="h-80 bg-black/5 animate-pulse rounded-xl" /></MemberLayout>;
  if (!data) return <MemberDataState title="Profile" error={error} />;
  const progress = membershipProgress(data.membership.startDate, data.membership.expiryDate);
  return <MemberLayout title="Profile" back="/member"><div className="space-y-5"><div className="text-center"><div className="w-20 h-20 mx-auto rounded-full bg-black text-white flex items-center justify-center text-2xl font-bold">{data.profile.avatar}</div><h1 className="text-xl font-bold mt-3">{data.profile.name}</h1><p className="text-sm text-black/50">{data.profile.memberId} · {data.profile.gym}</p></div><div className="border border-black/10 rounded-2xl p-5"><div className="flex justify-between mb-4"><span className="flex gap-2 font-semibold"><Dumbbell className="w-5 h-5" /> Membership</span><span className="text-xs bg-black text-white rounded-full px-2.5 py-1">{data.membership.status}</span></div><div className="grid grid-cols-2 gap-3 text-sm"><div><p className="text-xs text-black/50">Plan</p><b>{data.membership.plan}</b></div><div><p className="text-xs text-black/50">Price</p><b>${data.membership.price}</b></div><div><p className="text-xs text-black/50">Start</p><b>{data.membership.startDate}</b></div><div><p className="text-xs text-black/50">Expiry</p><b>{data.membership.expiryDate}</b></div></div><p className="text-xs text-black/50 mt-4">{progress.remaining} days remaining</p></div><div className="border border-black/10 rounded-2xl p-5"><h3 className="font-semibold">Personal information</h3><Row icon={Phone} label="Phone" value={data.profile.phone} /><Row icon={Mail} label="Email" value={data.profile.email} /><Row icon={Calendar} label="Member since" value={data.profile.joinDate} /></div></div></MemberLayout>;
}