import React from "react";
import { Link } from "react-router-dom";
import { Flame, CreditCard, CalendarCheck, ArrowRight } from "lucide-react";
import MemberLayout from "@/components/MemberLayout";
import MemberDataState from "@/components/member/MemberDataState";
import { useMemberPortal } from "@/lib/memberPortalStore";
import { membershipProgress, attendanceSummary } from "@/lib/memberPortalUtils";
export default function MemberDashboard() {
  const { data, loaded, error } = useMemberPortal();
  if (!loaded) return <MemberLayout><div className="space-y-4">{[1,2,3].map((i) => <div key={i} className="h-28 rounded-xl bg-black/5 animate-pulse" />)}</div></MemberLayout>;
  if (!data) return <MemberDataState error={error} />;
  const progress = membershipProgress(data.membership.startDate, data.membership.expiryDate);
  const attendance = attendanceSummary(data.attendance);
  const hour = new Date().getHours(); const greeting = hour < 12 ? "Good morning" : hour < 18 ? "Good afternoon" : "Good evening";
  return <MemberLayout><div className="space-y-5"><div><p className="text-sm text-black/50">{greeting},</p><h1 className="text-2xl font-bold">{data.profile.name}</h1></div><div className="border border-black/10 rounded-2xl p-5"><div className="flex justify-between"><div><p className="text-xs text-black/50">Membership</p><p className="text-lg font-bold">{data.membership.plan}</p></div><span className="h-fit px-2.5 py-1 rounded-full text-xs font-semibold bg-emerald-600 text-white">{data.membership.status}</span></div><div className="grid grid-cols-2 gap-3 my-4"><div><p className="text-xs text-black/50">Start date</p><b className="text-sm">{data.membership.startDate}</b></div><div><p className="text-xs text-black/50">Expiry date</p><b className="text-sm">{data.membership.expiryDate}</b></div></div><p className="text-xs text-black/50 mb-1.5">{progress.remaining} days remaining · {progress.pct}% used</p><div className="h-2 bg-black/5 rounded-full"><div className="h-full bg-black rounded-full" style={{ width: `${progress.pct}%` }} /></div></div><div className="border border-black/10 rounded-2xl p-5"><div className="flex justify-between"><span className="flex gap-2 font-semibold"><Flame className="w-5 h-5" /> Daily streak</span><b>{attendance.current} days</b></div><Link to="/member/attendance" className="mt-4 flex justify-center text-xs font-medium">View attendance <ArrowRight className="w-3 h-3" /></Link></div><div className="border border-black/10 rounded-2xl p-5"><div className="flex justify-between mb-3"><span className="flex gap-2 font-semibold"><CreditCard className="w-5 h-5" /> Payments</span><span className="text-xs bg-emerald-600 text-white rounded-full px-2.5 py-1">{data.balance.status}</span></div><div className="grid grid-cols-3 text-center"><div><p className="text-xs text-black/50">Price</p><b>${data.balance.price}</b></div><div><p className="text-xs text-black/50">Paid</p><b>${data.balance.paid}</b></div><div><p className="text-xs text-black/50">Balance</p><b>${data.balance.balance}</b></div></div></div><Link to="/member/profile" className="flex items-center justify-center gap-2 border border-black/10 rounded-xl p-4"><CalendarCheck className="w-5 h-5" /> View full profile</Link></div></MemberLayout>;
}