import React from "react";
import { Flame, Check, X, Calendar } from "lucide-react";
import MemberLayout from "@/components/MemberLayout";
import MemberDataState from "@/components/member/MemberDataState";
import { useMemberPortal } from "@/lib/memberPortalStore";
import { attendanceSummary } from "@/lib/memberPortalUtils";
const days = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
export default function MemberAttendance() {
  const { data, loaded, error } = useMemberPortal();
  if (!loaded) return <MemberLayout title="Attendance"><div className="h-80 bg-black/5 animate-pulse rounded-xl" /></MemberLayout>;
  if (!data) return <MemberDataState title="Attendance" error={error} />;
  const summary = attendanceSummary(data.attendance); const now = new Date(); const first = new Date(now.getFullYear(), now.getMonth(), 1).getDay(); const count = new Date(now.getFullYear(), now.getMonth() + 1, 0).getDate(); const cells = [...Array(first).fill(null), ...Array.from({ length: count }, (_, i) => i + 1)];
  return <MemberLayout title="Attendance" back="/member"><div className="space-y-5"><div className="bg-black text-white rounded-2xl p-5 text-center"><Flame className="w-8 h-8 mx-auto" /><p className="text-3xl font-bold mt-2">{summary.current} day streak</p></div><div className="border border-black/10 rounded-2xl p-5"><h3 className="font-semibold mb-3">Last 7 days</h3><div className="flex justify-between">{summary.week.map((item) => <div key={item.date} className="text-center"><p className="text-[10px] text-black/40">{item.day}</p><div className={`w-9 h-9 mt-2 rounded-full flex items-center justify-center ${item.attended ? 'bg-black text-white' : 'bg-black/5 text-black/40'}`}>{item.attended ? <Check className="w-4 h-4" /> : <X className="w-4 h-4" />}</div></div>)}</div></div><div className="border border-black/10 rounded-2xl p-5"><h3 className="flex gap-2 font-semibold mb-4"><Calendar className="w-4 h-4" /> {now.toLocaleDateString('en', { month: 'long', year: 'numeric' })}</h3><div className="grid grid-cols-7 gap-1">{days.map((day) => <div key={day} className="text-center text-[10px] text-black/40">{day}</div>)}{cells.map((day, index) => { if (!day) return <div key={`blank-${index}`} />; const key = `${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`; return <div key={key} className={`aspect-square rounded-lg flex items-center justify-center text-xs ${summary.dates.has(key) ? 'bg-black text-white' : 'bg-black/[0.02] text-black/40'}`}>{day}</div>; })}</div></div><div className="border border-black/10 rounded-xl p-4 text-center"><p className="text-2xl font-bold">{summary.monthCount}</p><p className="text-xs text-black/50">Check-ins this month</p></div></div></MemberLayout>;
}