import React from "react";
import { CreditCard, Check, Clock } from "lucide-react";
import MemberLayout from "@/components/MemberLayout";
import MemberDataState from "@/components/member/MemberDataState";
import { useMemberPortal } from "@/lib/memberPortalStore";
export default function MemberPayments() {
  const { data, loaded, error } = useMemberPortal();
  if (!loaded) return <MemberLayout title="Payments"><div className="h-80 bg-black/5 animate-pulse rounded-xl" /></MemberLayout>;
  if (!data) return <MemberDataState title="Payments" error={error} />;
  return <MemberLayout title="Payments" back="/member"><div className="space-y-5"><div className="border border-black/10 rounded-2xl p-5"><div className="flex justify-between mb-4"><span className="flex gap-2 font-semibold"><CreditCard className="w-5 h-5" /> Membership balance</span><span className="text-xs bg-emerald-600 text-white rounded-full px-2.5 py-1">{data.balance.status}</span></div><div className="grid grid-cols-3 gap-2 text-center"><div><p className="text-xs text-black/50">Price</p><b>${data.balance.price}</b></div><div><p className="text-xs text-black/50">Paid</p><b>${data.balance.paid}</b></div><div><p className="text-xs text-black/50">Balance</p><b>${data.balance.balance}</b></div></div><div className="flex justify-between text-sm border-t mt-4 pt-3"><span className="text-black/50">Renewal date</span><b>{data.balance.renewalDate}</b></div></div><div><h3 className="text-xs font-semibold uppercase tracking-wider text-black/40 mb-2">Payment history</h3>{data.payments.length === 0 ? <p className="text-sm text-black/45 text-center py-8 border rounded-xl">No payments recorded</p> : <div className="space-y-2">{data.payments.map((payment) => <div key={payment.id} className="border border-black/10 rounded-xl p-4 flex gap-3"><div className="w-10 h-10 bg-black/5 rounded-lg flex items-center justify-center"><Check className="w-5 h-5" /></div><div className="flex-1"><p className="text-sm font-semibold">${payment.amount} · {payment.method}</p><p className="text-xs text-black/50">{payment.date} · {payment.reference}</p></div><span className="text-xs font-semibold text-emerald-600">Paid</span></div>)}</div>}</div><div className="flex gap-2 bg-black/[0.02] rounded-xl p-3"><Clock className="w-4 h-4" /><p className="text-xs text-black/50">Payments shown here are the records confirmed by your gym.</p></div></div></MemberLayout>;
}