import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import { Dumbbell, Phone, KeyRound, ArrowRight, CheckCircle2, AlertCircle, Loader2, ArrowLeft } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import { joinGym } from "@/lib/memberPortalStore";
import { useAuth } from "@/lib/AuthContext";
const inputCls = "w-full px-3 py-3 rounded-lg border border-black/15 bg-white text-sm outline-none focus:border-black focus:ring-1 focus:ring-black";
export default function JoinGym() {
  const navigate = useNavigate();
  const { reloadRole } = useAuth();
  const [step, setStep] = useState("form");
  const [phone, setPhone] = useState("");
  const [joinToken, setJoinToken] = useState("");
  const [error, setError] = useState("");
  const verify = async (event) => { event.preventDefault(); setError(""); setStep("verifying"); try { await joinGym(phone.trim(), joinToken.trim()); await reloadRole(); setStep("success"); } catch (err) { setError(err?.response?.data?.error || err.message || "Verification failed"); setStep("error"); } };
  return <div className="min-h-screen bg-white text-black flex flex-col"><header className="h-14 flex items-center px-4 border-b border-black/10"><button onClick={() => navigate("/login")} className="p-2 -ml-2"><ArrowLeft className="w-5 h-5" /></button><div className="flex-1 flex justify-center items-center gap-2"><div className="w-7 h-7 rounded-lg bg-black flex items-center justify-center"><Dumbbell className="w-4 h-4 text-white" /></div><b>GymSync</b></div><div className="w-9" /></header><div className="flex-1 flex items-center justify-center px-5 py-8"><div className="w-full max-w-md"><AnimatePresence mode="wait">{step === "form" && <motion.div key="form" initial={{ opacity: 0 }} animate={{ opacity: 1 }}><h1 className="text-2xl font-bold">Join your gym</h1><p className="text-sm text-black/50 mt-1 mb-6">Enter your phone number and the join code your gym gave you.</p>{error && <p className="mb-4 p-3 bg-black/5 rounded-lg text-sm">{error}</p>}<form onSubmit={verify} className="space-y-4"><label className="block text-sm font-medium">Registered phone number<div className="relative mt-1.5"><Phone className="absolute left-3 top-3.5 w-4 h-4 text-black/40" /><input className={`${inputCls} pl-10`} value={phone} onChange={(e) => setPhone(e.target.value)} required /></div></label><label className="block text-sm font-medium">Join code<div className="relative mt-1.5"><KeyRound className="absolute left-3 top-3.5 w-4 h-4 text-black/40" /><input className={`${inputCls} pl-10`} value={joinToken} onChange={(e) => setJoinToken(e.target.value)} required /></div></label><button className="w-full flex items-center justify-center gap-2 px-4 py-3 rounded-lg bg-black text-white text-sm font-medium">Verify information <ArrowRight className="w-4 h-4" /></button></form></motion.div>}{step === "verifying" && <div className="text-center py-10"><Loader2 className="w-10 h-10 mx-auto animate-spin" /><p className="text-sm mt-4">Verifying your information…</p></div>}{step === "success" && <div className="text-center"><CheckCircle2 className="w-16 h-16 mx-auto mb-4" /><h1 className="text-2xl font-bold">Membership verified</h1><p className="text-sm text-black/50 mt-2 mb-6">Your exact membership information is now linked.</p><button onClick={() => navigate("/member")} className="w-full px-4 py-3 rounded-lg bg-black text-white">Continue to member app</button></div>}{step === "error" && <div className="text-center"><AlertCircle className="w-16 h-16 mx-auto mb-4 text-black/50" /><h1 className="text-2xl font-bold">We couldn't verify your information</h1><p className="text-sm text-black/50 mt-2 mb-6">{error}</p><button onClick={() => setStep("form")} className="w-full px-4 py-3 rounded-lg bg-black text-white">Try again</button></div>}</AnimatePresence></div></div></div>;
}